#	Run expect? installer


#	FIX postfix hardening
- command: chdir=/etc/postfix/ {{ item }}
  with_items:
  - postconf -e "smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, check_recipient_access mysql:/etc/postfix/mysql-virtual_recipient.cf, reject_unauth_destination, reject_unknown_recipient_domain, reject_non_fqdn_sender, reject_non_fqdn_recipient,  reject_unauth_destination, reject_unauth_pipelining, check_client_access hash:/etc/postfix/whitelist, reject_invalid_hostname, reject_rbl_client cbl.abuseat.org, reject_rbl_client bl.spamcop.net, reject_rbl_client opm.blitzed.org, reject_rbl_client zen.spamhaus.org, check_policy_service inet:127.0.0.1:10023, check_policy_service unix:private/policy-spf"
  - postconf -e "smtpd_client_restrictions = permit_mynetworks, permit_sasl_authenticated, check_client_access mysql:/etc/postfix/mysql-virtual_client.cf"
  - postconf -e "mydestination = {{inventory_hostname}}, localhost, localhost.localdomain"
  - postconf -e "smtpd_tls_cert_file=/etc/ssl/certs/{{inventory_hostname}}.crt"
  - postconf -e "smtpd_tls_key_file=/etc/ssl/private/{{inventory_hostname}}.key"
